### ISSUE TITLE
Release v2.5.9 potential Electron 26.1.0 bug

### ISSUE THREAD

**Issue by JJWatMyself** [LapsTimeOFF/DigiFlag_F1MV#98]
Appears Electron update from 25.3.2 to 26.1.0 has broken the app with release 2.5.9

https://github.com/LapsTimeOFF/DigiFlag_F1MV/blob/75d04d9f2f9bec684429d8d7d87116c12ba9f082/package.json

**Comment by JJWatMyself** [comment]
Issue exists on Ubuntu 22.04. Screenshot below.
![image](https://github.com/LapsTimeOFF/DigiFlag_F1MV/assets/22590445/97591d55-168f-4e6a-84a6-47daa1bfcde4)

**Comment by TheBaconCat** [comment]
This issue has been resolved with the updated v2.5.9

**Comment by JJWatMyself** [comment]
Confirmed is solved.  Thank you as always @TheBaconCat
